workflow_dir: /path/to/RADIAnT/workflow/

fastq_directory: /path/to/RADIAnT/example/RADICL/ 
sample_base: 
- mESC_2FA_n1_
output_directory: /path/to/RADIAnT/results/RADICL/
method:
- RADICL
dna_fastq_suffix: DNA.fastq
rna_fastq_suffix: RNA.fastq

species: mouse
gtf: /path/to/RADIAnT/resources/mouse/gencode.vM29.annotation.gtf.gz
genome_bins: /path/to/RADIAnT/resources/mouse/mm39.05kb.bed.gz
genes: /path/to/RADIAnT/resources/mouse/mm39.ncbiRefSeq.genes.bed.gz
blacklist: /path/to/RADIAnT/resources/mouse/mm39.excluderanges.bed.gz
rrna_fasta:  /path/to/RADIAnT/resources/mouse/arb-silva.de_2024-03-25_id1313737_tax_silva_trunc.fasta.gz

threads: 8
star_binary: # provide the path to the STAR binary, e.g. /home/user/STAR-2.7.9a/source/STAR
star_index: # provide the path to the STAR index you constructed, e.g. /home/user/Annotation/STARindex
bedtools_binary: # provide the path to the bedtools binary, e.g. /usr/bin/bedtools
samtools_binary: # provide the path to the samtools binary, /usr/bin/samtools
bamCoverage_binary: # provide the path to the bamCoverage binary, /home/user/.local/bin/bamCoverage
bbduk_script: # provide the path to the bbduk script, e.g. /home/user/software/bbmap/bbduk.sh
