workflow_dir: /path/to/RADIAnT/workflow/

fastq_directory: /path/to/RADIAnT/example/RedC/ 
sample_base: 
- Red-C_K562_N2_
output_directory: /path/to/RADIAnT/results/RedC/ 
method:
- Red-C
dna_fastq_suffix: DNA.fastq
rna_fastq_suffix: RNA5.fastq
rna_2_fastq_suffix: RNA3.fastq

species: human
gtf: /path/to/RADIAnT/resources/human/gencode.v45.annotation.gtf
genome_bins: /path/to/RADIAnT/resources/human/hg38_genome_5kb_bins_named.bed
genes: /path/to/RADIAnT/resources/human/gencode.v45.annotation.genes.bed
blacklist: /path/to/RADIAnT/resources/human/hg38-blacklist.v2.bed
rrna_fasta:  /path/to/RADIAnT/resources/human/Silva_rRNA_Homo_sapiens.fasta  

threads: 8
star_binary: # provide the path to the STAR binary, e.g. /home/user/STAR-2.7.9a/source/STAR
star_index: # provide the path to the STAR index you constructed, e.g. /home/user/Annotation/STARindex
bedtools_binary: # provide the path to the bedtools binary, e.g. /usr/bin/bedtools
samtools_binary: # provide the path to the samtools binary, /usr/bin/samtools
bamCoverage_binary: # provide the path to the bamCoverage binary, /home/user/.local/bin/bamCoverage
bbduk_script: # provide the path to the bbduk script, e.g. /home/user/software/bbmap/bbduk.sh

