method:
- Red-C

workflow_directory: /path/to/RADIAnT/workflow/ # Location of RADIAnT workflow (hodling snakemake file and scripts/ directory)

fastq_directory: /path/to/RADIAnT/example/RedC/ # Location of input fastq files
sample_base: # Common prefix of all fastq files with reads belonging to the experiment to be analysed
- Red-C_K562_N2_
# Specify the suffixes of the DNA and RNA reads. DO NOT include .gz even if the reads are compressed. 
# If for example your reads are named my_run.DNA.fastq and my_run.RNA.fastq, set sample_base: my_run., dna_fastq_suffix: DNA.fastq, rna_fastq_suffix: RNA.fastq
dna_fastq_suffix: DNA.fastq 
rna_fastq_suffix: RNA5.fastq 
rna_2_fastq_suffix: RNA3.fastq 

output_directory: /path/to/RADIAnT/results/RedC/ # Specify location results should be written to

species: human # currently supported: mouse and human
genome_fasta: /path/to/RADIAnT/resources/human/GRCh38.primary_assembly.genome.fa.gz # optional, can be omitted if STAR index already built
# if you don't have a genome fasta please download one, e.g. from https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/GRCh38.primary_assembly.genome.fa.gz
genome_bins: /path/to/RADIAnT/resources/human/hg38_5kb_bins_named.bed.gz
genes: /path/to/RADIAnT/resources/human/gencode.v45.annotation.genes.bed.gz
gtf: /path/to/RADIAnT/resources/human/gencode.v45.annotation.gtf.gz
blacklist: /path/to/RADIAnT/resources/human/hg38-blacklist.v2.bed.gz
rrna_fasta:  /path/to/RADIAnT/resources/human/Silva_rRNA_Homo_sapiens.fasta.gz

threads: 8
star_binary: # provide the path to the STAR binary, e.g. /home/user/STAR-2.7.9a/source/STAR
star_index: # provide the path to the STAR index you constructed, otherwise path to a directory the index should be written to 
bedtools_binary: # provide the path to the bedtools binary, e.g. /usr/bin/bedtools
samtools_binary: # provide the path to the samtools binary, /usr/bin/samtools
bamCoverage_binary: # provide the path to the bamCoverage binary, /home/user/.local/bin/bamCoverage
bbduk_script: # provide the path to the bbduk script, e.g. /home/user/software/bbmap/bbduk.sh

